### ISSUE TITLE
JSX syntax highlighting fails

### ISSUE THREAD

**Issue by braco** [ghempton/language-cjsx#2]
Single quote breaks:

```
render: ->
  <div>
       <p>You're .... </p>
```

Is this just repackaged coffee highlighting?

**Comment by ghempton** [comment]
This is just a simple port of the cjsx highlighting here: https://github.com/reactjs/sublime-react. Would love a PR to fix this issue :).

**Comment by braco** [comment]
Do you know of any syntax highlighters that actually work correctly? This looks like plain coffee highlighting, which seems like namespace pollution in that light.

**Comment by ahutchings** [comment]
This has been fixed upstream in sublime-react: https://github.com/reactjs/sublime-react/commit/5ded3cd92daaf4f5786316eca174429114b0ecc9.
